# Generated by Django 2.0.6 on 2018-06-11 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assesments',
            new_name='Assesment',
        ),
    ]
