# Generated by Django 2.0.6 on 2018-06-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180611_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
    ]
